# O bloco try/except no Python permite que um programa tente executar um conjunto de instruções e, se ocorrer uma exceção durante essa execução, o programa pode lidar com ela de forma adequada, sem interromper abruptamente sua execução. Ele consiste em duas partes principais: o bloco try, que contém o código a ser executado e que pode gerar exceções, e o bloco except, que trata essas exceções caso ocorram.